# Generated by Django 4.2.3 on 2023-08-16 12:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_user_name_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='name',
            field=models.TextField(max_length=50),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_number', models.TextField(max_length=255)),
                ('street_name', models.TextField(max_length=255)),
                ('city', models.TextField(max_length=255)),
                ('county', models.TextField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
